Repository wooga/atlas-appcenter, pull requests merged in 2020-12, with the labels that each got.

#26 Add retry logic for upload call
  src/integrationTest/groovy/wooga/gradle/appcenter/AppCenterPluginIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/appcenter/IntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/appcenter/tasks/AppCenterUploadTaskIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/appcenter/AppCenterConsts.groovy
  src/main/groovy/wooga/gradle/appcenter/AppCenterPlugin.groovy
  src/main/groovy/wooga/gradle/appcenter/AppCenterPluginExtension.groovy
  src/main/groovy/wooga/gradle/appcenter/api/AppCenterRest.groovy
  src/main/groovy/wooga/gradle/appcenter/internal/DefaultAppCenterPluginExtension.groovy
  src/main/groovy/wooga/gradle/appcenter/tasks/AppCenterUploadTask.groovy
  src/test/groovy/wooga/gradle/appcenter/api/AppCenterRestSpec.groovy
Labels: add, atlas-stream

#27 Fix deprecated publish flow
  src/integrationTest/groovy/wooga/gradle/appcenter/tasks/AppCenterUploadTaskIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/appcenter/api/AppCenterRest.groovy
  src/main/groovy/wooga/gradle/appcenter/tasks/AppCenterUploadTask.groovy
  src/test/groovy/wooga/gradle/appcenter/api/AppCenterRestSpec.groovy
Labels: atlas-stream, fix

#28 Improve error logging and tests
  Jenkinsfile
  src/integrationTest/groovy/wooga/gradle/appcenter/AppCenterPluginIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/appcenter/tasks/AppCenterUploadTaskIntegrationSpec.groovy
  src/integrationTest/resources/test.apk
  src/main/groovy/wooga/gradle/appcenter/api/AppCenterRest.groovy
  src/main/groovy/wooga/gradle/appcenter/tasks/AppCenterUploadTask.groovy
Labels: atlas-stream, improve

#31 Add missing default cases for several response handlers.
  src/main/groovy/wooga/gradle/appcenter/api/AppCenterRest.groovy
Labels: atlas-stream, improve

#33 Improve rate limit handling
  src/main/groovy/wooga/gradle/appcenter/api/AppCenterRest.groovy
Labels: atlas-stream, improve

#32 Refactors the AppCenter uploading logic into its own class
  src/main/groovy/wooga/gradle/appcenter/api/AppCenterReleaseUploader.groovy
  src/main/groovy/wooga/gradle/appcenter/api/AppCenterRest.groovy
  src/main/groovy/wooga/gradle/appcenter/tasks/AppCenterUploadTask.groovy
Labels: add, atlas-stream, change

#34 Refactor Uploader
  src/integrationTest/groovy/wooga/gradle/appcenter/AppCenterPluginIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/appcenter/api/AppCenterReleaseUploaderIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/appcenter/AppCenterConsts.groovy
  src/main/groovy/wooga/gradle/appcenter/api/AppCenterReleaseUploader.groovy
  src/main/groovy/wooga/gradle/appcenter/api/AppCenterRest.groovy
  src/main/groovy/wooga/gradle/appcenter/api/AppCenterRetryStrategy.groovy
  src/main/groovy/wooga/gradle/appcenter/tasks/AppCenterUploadTask.groovy
Labels: atlas-stream, improve
